config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :designs

  get 'numbers', to: 'categories#numbers'
  get 'letters', to: 'categories#letters'
  get 'objects', to: 'categories#objects'
end

# Ejemplo del programa de crazy boats, así se debe filtrar y organizar por categoría.
# en este caso las categoría serían números,letras, etc.

# Rails.application.routes.draw do
#   get 'categories/controller'
#   devise_for :users
#   root to: 'pages#home'

#   resources :boats, only: %i[index show new create] do
#     resources :bookings, only: %i[create new show]
#   end
#   resources :users do
#     resources :bookings, only: %i[index]
#   end

#   get 'fishing_boats', to: "categories#fishing_boats"
#   get 'party_boats', to: "categories#party_boats"
#   get 'yachts', to: "categories#yachts"

# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/design.rb
class Design < ApplicationRecord
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]
  def numbers
    @designs = Design.where(category: "Numbers")
  end

  def letters
    @designs = Design.where(category: "Letters")
  end

  def objects
    @designs = Design.where(category: "Objects")
  end
end


# Ejemplo del programa de Crazy boats:

# class CategoriesController < ApplicationController
#   skip_before_action :authenticate_user!
#   def fishing_boats
#     @boats = Boat.where(category: "Fishing")
#   end

#   def yachts
#     @boats = Boat.where(category: "Yacht")
#   end

#   def party_boats
#     @boats = Boat.where(category: "Party")
#   end
# end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :set_design, only: %i[ show ]

  def index
    @designs = Design.all
  end

  def show
    set_design
    @design = Design.find(params[:id])
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)

    if @design.save!
      redirect_to @design, notice: "Design was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def design_params
      params.require(:design).permit(:title, :category, :photo) #photos: [] if you want to allow multiple photos?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/letters.html.erb
<div class="letters-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Letters</h1>
  <%= render 'shared/design_card_display' %>
</div>
<%= render 'shared/footer' %>

app/views/categories/numbers.html.erb
<div class="numbers-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Numbers</h1>
  <%= render 'shared/design_card_display' %>
</div>

<%= render 'shared/footer' %>

app/views/categories/objects.html.erb
<div class="objects-main-container">
  <%= link_to root_path, class: "back-button" do %>
    <h3> <-- Back </h3>
  <% end %>
  <h1 class="category-title">Objects / Landscapes </h1>
  <%= render 'shared/design_card_display' %>
</div>

<%= render 'shared/footer' %>

app/views/designs/_form.html.erb
<%= simple_form_for(@design) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.title %></td>
        <td><%= design.category %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form', design: @design %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @design.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @design.category %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>J</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-content-container">
  <div class="banner">
    <h1 class="banner-title">QQL Atlas</h1>
    <p class="banner-description">
      QQL is a collaborative experiment in generative art by Tyler Hobbs and Dandelion Wist Mané.
    </p>

    <p class="banner-description">
      This gallery is a tribute to these artists and their work, by curating and displaying cool outputs in different visual categories of the QQL Algorithm.
    </p>
  </div>

  <div class="cards-container">
    <div class="col-lg-4">
      <%= link_to letters_path do %>
        <p>Letters</p>
        <%= image_tag('letter_u_2.png') %>
      <% end %>
    </div>

    <div class="col-lg-4">
      <%= link_to numbers_path do %>
        <p>Numbers</p>
        <%= image_tag('number_7.png') %>
      <% end %>
    </div>

    <div class="col-lg-4">
      <%= link_to objects_path do %>
        <p>Landscapes / Objects </p>
        <%= image_tag('landscape_wave2.png') %>
      <% end %>
    </div>
  </div>

  <div class="more-categories">
    <p>More categories soon...</p>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_design_card_display.html.erb
<div class="designs-cards-cointainer">
  <div class="designs-flex-container">
    <% @designs.each do |design| %>
      <div class="design-card">
        <h5 class="card-title"><%= design.title%> </h5>
        <div class="design-card-image">
        <% if design.photo.attached? %>
          <%= cl_image_tag design.photo.key, height: 350, width: 280, crop: :fill %>
         <% end %>
       </div>
      </div>
    <% end %>
   </div>
</div>

app/views/shared/_footer.html.erb
  <div class="footer">
  <a href="http://twitter.com/juaneseth">
    <p>By @juaneseth</p>
  </a>
  </div>